// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConf() {
  return window['go']['main']['App']['GetConf']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SyncConf(arg1, arg2) {
  return window['go']['main']['App']['SyncConf'](arg1, arg2);
}
