// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {global} from '../models';
import {main} from '../models';

export function GetConf():Promise<global.Config>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<main.RetrueMsg>;

export function SyncConf(arg1:string,arg2:string):Promise<void>;
